### PR TITLE
Cypress

### PR DESCRIPTION
**Pull request by Zonkman**
Basic Cypress testing makes sure the elements of the main page of the app, and particularly the chat window, is working properly. This doesn't test anything in the actual gameplay (to do this we may need Phaser testing)

### CODE REVIEW

**Comment by Zonkman** [comment]
there was a merge conflict in package.json and package-lock.json . i decided to use my version since it has more cypress features installed, however, there are many areas in which "dev=true" in master have been removed. this probably makes the production build unnecessarily big. now fixing

**Comment by Zonkman** [comment]
lol

**Comment by Zonkman** [comment]
it's fixed

**Comment by jsun454** [comment]
LGTM

**Pull request merged**
